export enum LevelUser {
    ADMIN = "ADMIN",
    OPERATOR = "OPERATOR",
    PROGDI = "PROGDI",
    BAK = "BAK",
    DIREKTUR = "DIREKTUR",
    DOSEN = "DOSEN",
    MAHASISWA = "MAHASISWA",
    KEUANGAN = "KEUANGAN",
    PUSTAKA = "PUSTAKA",
    MABA = "MABA",
    PANITIA = "PANITIA",
    FAKULTAS = "FAKULTAS",
    LPJM = "LPJM",
    ADMPROGS2 = "ADMPROGS2",
    ADMPROGS3 = "ADMPROGS3",
    MBKM = "MBKM"
}
